version: '2'
services:
  fluentd-client:
    container_name: fluentd-client
    build: fluentd
    ports:
      - "9880:9880"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    links:
      - aggregator

  aggregator:
    container_name: aggregator
    build: aggregator
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./aggregator/fluent.conf:/fluentd/etc/fluent.conf

  fluentbit-client:
    container_name: fluentbit-client
    image: fluent/fluent-bit
    ports:
      - "9883:9883"
    volumes:
      - ./fluent-bit-client.conf:/fluent-bit/etc/fluent-bit.conf
    links:
      - aggregator
