# docker-compose -f ./docker-compose-fluentbit.yml up --build -d --scale fluentd-client=1
# docker-compose -f ./docker-compose-fluentbit.yml down --remove-orphans

version: '2'
services:
  fluentd-client:
    image: fluent/fluentd:v1.14.0-debian-1.0
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/sb_api.log:/fluentd/etc/sb_api.log
    links:
      - aggregator

  aggregator:
    container_name: aggregator
    image: fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  fluentbit-client:
    container_name: fluentbit-client
    image: fluent/fluent-bit
    ports:
      - "9883:9883"
    volumes:
      - ./fluent-bit-client.conf:/fluent-bit/etc/fluent-bit.conf
    links:
      - aggregator
